example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Alanna',
        'last_login': request.COOKIES['last_login'],
        }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Alanna',
        'last_login': request.COOKIES['last_login'],
        }
    return render(request, "wishlist_ajax.html", context)

# def show_wishlist_item(request):


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")   

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {
        'form': form,
        'nama': 'Alanna',
        }
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {'nama': 'Alanna',}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

def create_wishlist(request):
    # if request.method == 'POST'
    return

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login | Wishlist</title>
{% endblock meta %}

{% block content %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
    * {
        font-family: "Work Sans";
        text-align:center;
        vertical-align: middle;
        color: #2e3c4d;
    }
    td, input {
        text-align: left; 
    }
    form {
        border-radius:0.5em; 
        box-shadow: 0px 0px 7px rgba(128, 128, 128, 0.211);   
        background-color: rgba(178, 178, 178, 0.211);   
        margin: auto;
        width: 270px;
        padding: 1em;
        border-radius: 1em;
    }
    h1, a, a.visited {
        font-family: "Work Sans";
        color:#413f76;
    }
    body {
        background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
    }
</style>


<nav class="navbar navbar-expand-lg navbar-color">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ nama }}</a>
      <button class="btn btn-outline-success"><a class="link-dark" href="{% url 'wishlist:login' %}">Login</a></button>
    </div>
</nav>

</br>
</br>

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td></br><input class="btn login_btn" type="submit" value="Login" style="background-color:rgba(255, 255, 255, 0.264)"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    </br>
    <p>Belum mempunyai akun?  <a href="{% url 'wishlist:register' %}">Buat Akun</a></p>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun | Wishlist</title>
{% endblock meta %}

{% block content %} 
<!doctype html> 
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">

<style>
    * {
        font-family: "Work Sans";
        text-align: left; 
         vertical-align:text-top;
    }
    h1 {
         text-align: center;
         color:#413f76;
    }
    th {
         font-size: large;
    }
    body {
         background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
    }  
    form {
        margin:auto; 
        width: 800px; 
        padding: 1em; 
        border-radius: 1em; 
        font-size: small; 
        background-color: rgba(204, 204, 204, 0.277); 
        box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.211); 
    }
</style>


<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ nama }}</a>
      <button class="btn btn-outline-success"><a class="link-dark" href="{% url 'wishlist:login' %}">Login</a></button>
    </div>  
</nav>

</br>
</br>

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  
    </br>
        <form method="POST">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td></br><input class="btn login_btn" type="submit" value="Daftar" style="background-color:rgba(255, 255, 255, 0.8)"></td>
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<title>Wishlist</title>
{% endblock meta %}

{% block content %}
<!doctype html>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
    * {
        font-family: "Work Sans";
        text-align: left;
        vertical-align: middle;
        color: #2e3c4d;
    }
    table {
        margin: auto;
        background-color: rgba(255, 255, 255, 0.55); 
        border-radius:0.5em; 
        box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.211); 
    }
    td {
        font-family:system-ui;
        color:#413f76;
    }
    h3, h5 {
        padding-left:11%;
        font-family:"Work Sans";
    }
    body {
        background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
    }

</style>

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{ nama }}</a>
    <button class="btn btn-outline-success"><a class="link-dark" href="{% url 'wishlist:logout' %}">Logout</a></button>
  </div>
</nav>

</br></br>

<h3 style="font-weight:bolder; font-size: 200%; color:#434a9b;">{{ nama }}'s Wishlist</h3>
</br>

<table class="table" style="width:80%; border:1px solid rgba(255, 255, 255, 0);">
    <div>
        <tr style="height:35px; font-size:80%">
            <td style="width:30%">Nama Barang</td>
            <td style="width:20%">Harga Barang</td>
            <td style="width:50%">Deskripsi</td>
        </tr>
    </div>
    {% for barang in list_barang %}
        <tr>
            <td style="font-weight:600; color:#2e3c4d">{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
    {% endfor %}
</table>
</br>

<h5 style="font-size:small">Sesi terakhir login: {{ last_login }}</h5>
</br>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<title>Wishlist</title>
{% endblock meta %}

{% block content %}
<!doctype html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $.get("https://localhost:8000/wishlist/json/", function(data) {
            for (i=0; i<data.length; i++){
                $(".barang").append(
                    `<tr>
                        <td>${data[i].fields.nama_barang}</td>
                        <td>${data[i].fields.harga_barang}</td><
                        td>${data[i].fields.deskripsi}</td></tr>`
                )
            }
        });

        $("#submit_btn").click(function(){
            $.post("http://localhost:8000/wishlist/ajax/submit", {
                nama_barang: $("#nama_barang").val(),
                harga_barang:parseInt($("#harga_barang").val()),
                deskripsi:$("#deskripsi").val()
            } )
        })
    });
</script>

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">
<style>
    * {
        font-family: "Work Sans";
        text-align: left;
        vertical-align: middle;
        color: #2e3c4d;
    }
    table {
        margin: auto;
        background-color: rgba(255, 255, 255, 0.55); 
        border-radius:0.5em; 
        box-shadow: 0px 0px 20px rgba(128, 128, 128, 0.211); 
    }
    td {
        font-family:system-ui;
        color:#413f76;
    }
    h3, h5 {
        text-align:center;
    }
    body {
        background-image: url(https://img.freepik.com/free-vector/gradient-blur-pink-blue-abstract-background_53876-117324.jpg);
    }

</style>

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{ nama }}</a>
    <button class="btn btn-outline-success"><a class="link-dark" href="{% url 'wishlist:logout' %}">Logout</a></button>
  </div>
</nav>

</br></br>

<h3 style="font-weight:bolder; font-size: 200%; color:#434a9b;">{{ nama }}'s Wishlist</h3>
</br>

<form method="POST" action="">
    {% csrf_token %}
    <table class="table" style="width:30%; border:1px solid rgba(255, 255, 255, 0);">
        <tr>
        <td>Nama Barang:</td>
        <td><input type="text" name="nama_barang" placeholder="Nama Barang" id="nama_barang" class="form-control"/></td>
      </tr>
  
      <tr>
        <td>Harga Barang:</td>
        <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="harga_barang"/></td>
      </tr>
      <tr>
        <td>Deskripsi:</td>
        <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="deskripsi"/></td>
      </tr>
  
      <tr>
        <td></td>
        <td><button id="submit_btn">Tambah Wishlist Baru</button></td>    
      </tr>
    </table>
  </form>


<table class="table" style="width:80%; border:1px solid rgba(255, 255, 255, 0);">
    <div>
        <tr style="height:35px; font-size:80%">
            <td style="width:30%">Nama Barang</td>
            <td style="width:20%">Harga Barang</td>
            <td style="width:50%">Deskripsi</td>
        </tr>
    </div>
    {% for barang in list_barang %}
        <tr>
            <td style="font-weight:600; color:#2e3c4d">{{barang.nama_barang}}</td>
            <td>{{barang.harga_barang}}</td>
            <td>{{barang.deskripsi}}</td>
        </tr>
    {% endfor %}
</table>
</br>

<h5 style="font-size:small">Sesi terakhir login: {{ last_login }}</h5>
</br>


{% endblock content %}